### ISSUE TITLE
Inverted results for difficulty compared to mirt

### ISSUE THREAD

**Issue by karloskar** [eribean/girth_mcmc#11]
Just did a quick comparison for a 2PL model on a dichotomous dataset between the R package mirt and girth_mcmc. Are there any specific reasons that the scale for the difficulty values are inverted (for lack of a better term)?

![girth_vs_mirt_1](https://user-images.githubusercontent.com/782033/135428357-4e2b905d-0e3c-4843-91f5-8d5f7916852b.png)

**Comment by karloskar** [comment]
Should have read the manual for mirt more closely 🤦‍♂️
There I would have found the argument `IRTpars` which 
> "convert slope intercept parameters into traditional IRT parameters"

**Comment by eribean** [comment]
@karloskar Apologies for not getting back to you sooner, but it sounds like you figured it out.
